### ISSUE TITLE
Alignment of the top text

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9-Menu-GFX-Generator#2]
Left option should be left-aligned, center option should be centered, right option should right-aligned. How to do this?

**Comment by Shadowtrance** [comment]
Not sure about this to be honest.
The L and R text/arrows are about 20 pixels combined (rough guess) from the purple edge and Titlekey Decrypt is right up against L and Emunand Options overlaps R as it is now. And the other options also overlap R when you switch through them.
I could always move the L R indicators to the bottom instead then they wouldn't overlap i guess.

**Comment by d0k3** [comment]
Don't depend design choices on this code. This code has to change, not your design in that case :). The L/R text overlapping should be easily fixable.

**Comment by Shadowtrance** [comment]
Yeah having the L R at the top just makes sense i guess. So i won't change that. :)

**Comment by d0k3** [comment]
Solved in https://github.com/d0k3/Decrypt9-Menu-GFX-Generator/commit/58e6914bb8eb1737087a963ad823904223b7505e
