### ISSUE TITLE
Description text

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9-Menu-GFX-Generator#3]
Shadowtrances last design had a description text with (automatic?) word wrapping on the right side of the menu. How to do this in ImageMagick?

**Comment by Shadowtrance** [comment]
The description text wasn't wrapping (automatically), i manually aligned it by moving it to a new line with enter if it went over the edge of the background. :)

**Comment by d0k3** [comment]
It should automatically wrap - would make things much easier for you. If possible, of course.

**Comment by Shadowtrance** [comment]
Ah yeah for sure. We just need to figure out how to do it with ImageMagick. :)

**Comment by pixel-stuck** [comment]
I think maybe what we need to do is have some sort of limiting of how far it can go like having a pixel limit i.e. limit the text size across to, let's say 50 pixels then when the typing reaches that limit it'll simply go to the next line, I'm looking into if this is possible with imagemagick

**Comment by pixel-stuck** [comment]
aaaaaand here we are, you simply give the text an image size (we may have to generate separate text image files and then manually align those, ugh) then, according to the imagemagick docs it looks like it'll wrap.... now if this doesn't work it actually accepts a newline character just like printf does so you can do "text line 1\ntext line 2\ntext line 3"

and it'll look like 

text line 1
text line 2
text line 3

**Comment by d0k3** [comment]
I think I got something better... Just use 'caption:' instead of 'label:' to generate the description texts. Check out commit https://github.com/d0k3/Decrypt9-Menu-GFX-Generator/commit/026bc22cb1b1c67ec691ed49008e8f4f347dbfd1

Shadowtrance, can you try around with that? See the new defines on top of main.c. 'Gravity' is where the text is drawn to (if unsure, just try 'North', 'NorthWest' etc...). Description texts go into the structs in d9menu.h.

**Comment by pixel-stuck** [comment]
Yeah that's what I was planning on doing in the future, the main problem with caption though is if you don't give it a horizontal resolution it'll automatically wrap every single word... So we mainly need to know when to use it and when to not use it

**Comment by d0k3** [comment]
Closing this for now, the caption solution works for this one, but we need to keep in mind that caption is not the best solution everywhere.
