### ISSUE TITLE
Handling of submenus

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9-Menu-GFX-Generator#4]
That's fully up to the theme designer(s), of course, but maybe submenus should be shown in a different manner? For example, show the original menu on the left (top entry selected), and the submenu on the right. Also, what goes in the top line then? (maybe just the centered name of the current menu)

**Comment by Shadowtrance** [comment]
I think it's fine as it is now, plus getting it to fit on the right side with the main entries on the left side would be a pain as "some" of the sub entries, namely Dump LocalFriendCodeSeed_B JUST fit in the selected option marker image.
Maybe just the centered name added to the top would be good.

**Comment by d0k3** [comment]
Looking good for now (see commit https://github.com/d0k3/Decrypt9-Menu-GFX-Generator/commit/58e6914bb8eb1737087a963ad823904223b7505e). Issue solved for now, unless design choices lead us to think this over. Closing this for now.
