### ISSUE TITLE
Creating the entry labels more elegantly?

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9-Menu-GFX-Generator#6]
Well, this is a nice to have rather than an issue... Is there any way we could combine the active entry labels with the active entry background when creating them? This would be more elegant than creating base images for each cursor position! Text placement relative to the background and opacity are possible issues here.

**Comment by pixel-stuck** [comment]
So you want to have the base images have the text drawn over them? I believe that would require that we write more base images though wouldn't it?

**Comment by d0k3** [comment]
No, I meant the temporary label images (those that only contain the text right now). Anyways, with the last cleanup, how things are done now should already be fine. I think we shouldn't put any work into this non-issue :). Closing it for now to not generate confusion.
